import { Router } from 'express';
import { Project, RuleSet, Site, Zone } from '../models/index.js';
import { requireAuth, requireProjectAccess, ensureProjectAccess } from '../middleware/auth.js';
import { asyncHandler } from '../utils/async-handler.js';
import { ApiError } from '../utils/api-error.js';
import { audit } from '../services/audit.service.js';

const router=Router();router.use(requireAuth);
router.get('/projects/:projectId/rule-set',requireProjectAccess,asyncHandler(async(req,res)=>{const p=await Project.findById(req.params.projectId).lean();if(!p)throw new ApiError(404,'Project not found');const r=p.ruleSetId?await RuleSet.findById(p.ruleSetId).lean():null;res.json(r);}));
router.post('/projects/:projectId/rule-sets/versions',requireProjectAccess,asyncHandler(async(req,res)=>{const project=await Project.findById(req.params.projectId);if(!project)throw new ApiError(404,'Project not found');const current=project.ruleSetId?await RuleSet.findById(project.ruleSetId).lean():null;const version=Number(current?.version||0)+1;const doc=await RuleSet.create({organizationId:req.auth.organizationId,code:req.body.code||current?.code||`${project.code}_RULES`,name:req.body.name||current?.name||`${project.name} Rules`,useCaseCodes:[project.useCaseCode],version,status:'DRAFT',description:req.body.description||current?.description,rules:req.body.rules||current?.rules||[],tarpActions:req.body.tarpActions||current?.tarpActions||{}});await audit({req,projectId:project._id,action:'RULESET_VERSION_CREATED',resourceType:'RuleSet',resourceId:doc._id,newState:doc.toObject()});res.status(201).json(doc);}));
router.post('/rule-sets/:id/approve',asyncHandler(async(req,res)=>{const r=await RuleSet.findOne({_id:req.params.id,organizationId:req.auth.organizationId});if(!r)throw new ApiError(404,'Rule set not found');r.status='APPROVED';r.approvedAt=new Date();r.approvedBy=req.auth.userId;await r.save();res.json(r);}));
router.post('/projects/:projectId/rule-sets/:id/activate',requireProjectAccess,asyncHandler(async(req,res)=>{const [project,rule]=await Promise.all([Project.findById(req.params.projectId),RuleSet.findById(req.params.id)]);if(!project||!rule)throw new ApiError(404,'Project or rule set not found');if(!['APPROVED','ACTIVE'].includes(rule.status))throw new ApiError(409,'Rule set must be approved before activation');project.ruleSetId=rule._id;await project.save();rule.status='ACTIVE';await rule.save();await audit({req,projectId:project._id,action:'RULESET_ACTIVATED',resourceType:'RuleSet',resourceId:rule._id,newState:rule.toObject()});res.json({projectId:project._id,ruleSet:rule});}));
router.post('/projects/:projectId/sites',requireProjectAccess,asyncHandler(async(req,res)=>res.status(201).json(await Site.create({organizationId:req.auth.organizationId,projectId:req.params.projectId,name:req.body.name,code:req.body.code,type:req.body.type||'SITE',parentId:req.body.parentId,level:req.body.level||0,geometry:req.body.geometry,metadata:req.body.metadata||{}}))));
router.post('/projects/:projectId/zones',requireProjectAccess,asyncHandler(async(req,res)=>res.status(201).json(await Zone.create({organizationId:req.auth.organizationId,projectId:req.params.projectId,siteId:req.body.siteId,name:req.body.name,code:req.body.code,type:req.body.type||'ZONE',geometry:req.body.geometry,designNotes:req.body.designNotes,responsibleEngineerId:req.body.responsibleEngineerId,metadata:req.body.metadata||{}}))));
export default router;
