import { Router } from 'express';
import { BacktestRun, CorrelationModel } from '../models/index.js';
import { requireAuth } from '../middleware/auth.js';
import { asyncHandler } from '../utils/async-handler.js';
import { ApiError } from '../utils/api-error.js';
import { executeBacktest, validateGraph } from '../services/correlation.service.js';
import { audit } from '../services/audit.service.js';

const router=Router(); router.use(requireAuth);
router.get('/projects/:projectId/correlation-models',asyncHandler(async(req,res)=>res.json(await CorrelationModel.find({projectId:req.params.projectId,organizationId:req.auth.organizationId}).sort({updatedAt:-1}).lean())));
router.post('/correlation-models',asyncHandler(async(req,res)=>{const graph=req.body.graphJson||{nodes:[],edges:[]};const validation=validateGraph(graph);const model=await CorrelationModel.create({organizationId:req.auth.organizationId,projectId:req.body.projectId,name:req.body.name,purpose:req.body.purpose,scope:req.body.scope||{},ownerId:req.auth.userId,status:'DRAFT',versions:[{version:1,graphJson:graph,validationResult:validation,status:'DRAFT',checksum:validation.checksum}]});res.status(201).json(model);}));
router.put('/correlation-models/:id/versions/:v',asyncHandler(async(req,res)=>{const m=await CorrelationModel.findOne({_id:req.params.id,organizationId:req.auth.organizationId});if(!m)throw new ApiError(404,'Correlation model not found');const v=Number(req.params.v);const validation=validateGraph(req.body.graphJson);const idx=m.versions.findIndex(x=>x.version===v);const item={version:v,graphJson:req.body.graphJson,schemaVersion:1,validationResult:validation,status:'DRAFT',checksum:validation.checksum};if(idx>=0)m.versions[idx]=item;else m.versions.push(item);m.status='DRAFT';await m.save();res.json({modelId:m._id,version:v,validation});}));
router.post('/correlation-models/:id/backtests',asyncHandler(async(req,res)=>{const m=await CorrelationModel.findOne({_id:req.params.id,organizationId:req.auth.organizationId}).lean();if(!m)throw new ApiError(404,'Correlation model not found');const version=Number(req.body.version||m.versions.at(-1)?.version||1);const run=await BacktestRun.create({projectId:m.projectId,modelId:m._id,modelVersion:version,startAt:new Date(req.body.startAt),endAt:new Date(req.body.endAt),status:'QUEUED'});setImmediate(()=>executeBacktest(run._id));res.status(202).json(run);}));
router.get('/backtests/:id',asyncHandler(async(req,res)=>{const r=await BacktestRun.findById(req.params.id).lean();if(!r)throw new ApiError(404,'Backtest not found');res.json(r);}));
router.post('/correlation-models/:id/versions/:v/submit',asyncHandler(async(req,res)=>{const m=await CorrelationModel.findOne({_id:req.params.id,organizationId:req.auth.organizationId});if(!m)throw new ApiError(404,'Model not found');const item=m.versions.find(x=>x.version===Number(req.params.v));if(!item)throw new ApiError(404,'Version not found');if(!item.validationResult?.valid)throw new ApiError(409,'Graph validation failed');item.status='SUBMITTED';item.submittedAt=new Date();m.status='SUBMITTED';await m.save();res.json(m);}));
router.post('/correlation-models/:id/versions/:v/approve',asyncHandler(async(req,res)=>{const m=await CorrelationModel.findOne({_id:req.params.id,organizationId:req.auth.organizationId});if(!m)throw new ApiError(404,'Model not found');const item=m.versions.find(x=>x.version===Number(req.params.v));if(!item)throw new ApiError(404,'Version not found');item.status='APPROVED';item.approvedAt=new Date();item.approvedBy=req.auth.userId;m.status='APPROVED';await m.save();await audit({req,projectId:m.projectId,action:'CORRELATION_MODEL_APPROVED',resourceType:'CorrelationModel',resourceId:m._id,reason:req.body.note});res.json(m);}));
router.post('/correlation-models/:id/versions/:v/activate',asyncHandler(async(req,res)=>{const m=await CorrelationModel.findOne({_id:req.params.id,organizationId:req.auth.organizationId});if(!m)throw new ApiError(404,'Model not found');const item=m.versions.find(x=>x.version===Number(req.params.v));if(!item||item.status!=='APPROVED')throw new ApiError(409,'Only approved versions can be activated');m.activeVersion=item.version;m.status='ACTIVE';await m.save();await audit({req,projectId:m.projectId,action:'CORRELATION_MODEL_ACTIVATED',resourceType:'CorrelationModel',resourceId:m._id});res.json(m);}));
export default router;
