import { Router } from 'express';
import crypto from 'node:crypto';
import { Dashboard, DashboardVersion, DerivedReading, LatestState } from '../models/index.js';
import { requireAuth } from '../middleware/auth.js';
import { asyncHandler } from '../utils/async-handler.js';
import { ApiError } from '../utils/api-error.js';
import { audit } from '../services/audit.service.js';

const router=Router(); router.use(requireAuth);
router.get('/dashboards',asyncHandler(async(req,res)=>{const q={organizationId:req.auth.organizationId}; if(req.query.projectId) q.projectId=req.query.projectId; const rows=await Dashboard.find(q).populate('currentPublishedVersionId currentDraftVersionId').lean(); res.json(rows);}));
router.post('/dashboards',asyncHandler(async(req,res)=>{const d=await Dashboard.create({organizationId:req.auth.organizationId,projectId:req.body.projectId,name:req.body.name||'Dashboard',ownerId:req.auth.userId,templateType:req.body.templateType}); const v=await DashboardVersion.create({dashboardId:d._id,versionNo:1,status:'DRAFT',layoutJson:req.body.layoutJson||{widgets:[],layout:{}},schemaVersion:1,createdBy:req.auth.userId}); d.currentDraftVersionId=v._id;await d.save();res.status(201).json({dashboard:d,version:v});}));
router.put('/dashboards/:id/draft',asyncHandler(async(req,res)=>{const d=await Dashboard.findOne({_id:req.params.id,organizationId:req.auth.organizationId});if(!d)throw new ApiError(404,'Dashboard not found');let v=d.currentDraftVersionId?await DashboardVersion.findById(d.currentDraftVersionId):null;if(!v||v.status!=='DRAFT'){const last=await DashboardVersion.findOne({dashboardId:d._id}).sort({versionNo:-1});v=await DashboardVersion.create({dashboardId:d._id,versionNo:(last?.versionNo||0)+1,status:'DRAFT',layoutJson:req.body.layoutJson||{},schemaVersion:1,createdBy:req.auth.userId});d.currentDraftVersionId=v._id;await d.save();}else{v.layoutJson=req.body.layoutJson||v.layoutJson;await v.save();}res.json(v);}));
router.post('/dashboards/:id/publish',asyncHandler(async(req,res)=>{const d=await Dashboard.findOne({_id:req.params.id,organizationId:req.auth.organizationId});if(!d)throw new ApiError(404,'Dashboard not found');const v=await DashboardVersion.findById(d.currentDraftVersionId);if(!v)throw new ApiError(409,'No draft to publish');v.status='PUBLISHED';v.publishedAt=new Date();v.checksum=crypto.createHash('sha256').update(JSON.stringify(v.layoutJson)).digest('hex');await v.save();if(d.currentPublishedVersionId)await DashboardVersion.updateOne({_id:d.currentPublishedVersionId},{$set:{status:'SUPERSEDED'}});d.currentPublishedVersionId=v._id;d.currentDraftVersionId=undefined;await d.save();await audit({req,projectId:d.projectId,action:'DASHBOARD_PUBLISHED',resourceType:'DashboardVersion',resourceId:v._id,newState:v.toObject()});res.json(v);}));
router.post('/dashboards/:id/clone',asyncHandler(async(req,res)=>{const source=await Dashboard.findOne({_id:req.params.id,organizationId:req.auth.organizationId}).lean();if(!source)throw new ApiError(404,'Dashboard not found');const sv=await DashboardVersion.findById(source.currentPublishedVersionId||source.currentDraftVersionId).lean();const d=await Dashboard.create({organizationId:req.auth.organizationId,projectId:req.body.projectId||source.projectId,name:req.body.name||`${source.name} Copy`,ownerId:req.auth.userId,templateType:source.templateType});const v=await DashboardVersion.create({dashboardId:d._id,versionNo:1,status:'DRAFT',layoutJson:sv?.layoutJson||{},createdBy:req.auth.userId});d.currentDraftVersionId=v._id;await d.save();res.status(201).json({dashboard:d,version:v});}));
router.post('/widget-data/query',asyncHandler(async(req,res)=>{const queries=Array.isArray(req.body.queries)?req.body.queries:[];const out=[];for(const q of queries.slice(0,50)){if(q.mode==='latest'){const row=await LatestState.findOne({projectId:q.projectId,parameterCode:q.parameterCode,...(q.instrumentId?{instrumentId:q.instrumentId}:{})}).sort({observedAt:-1}).lean();out.push({key:q.key||q.parameterCode,data:row});}else{const from=new Date(q.from||Date.now()-24*3600000),to=new Date(q.to||Date.now());const rows=await DerivedReading.find({projectId:q.projectId,parameterCode:q.parameterCode,observedAt:{$gte:from,$lte:to},...(q.instrumentId?{instrumentId:q.instrumentId}:{})}).sort({observedAt:1}).limit(5000).lean();out.push({key:q.key||q.parameterCode,data:rows});}}res.json({results:out});}));
export default router;
