import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import compression from 'compression';
import morgan from 'morgan';
import rateLimit from 'express-rate-limit';
import swaggerUi from 'swagger-ui-express';
import { env } from './config/env.js';
import { correlationId } from './middleware/correlation-id.js';
import { notFound, errorHandler } from './middleware/error.js';
import authRoutes from './routes/auth.routes.js';
import templateRoutes from './routes/templates.routes.js';
import projectRoutes from './routes/projects.routes.js';
import assetRoutes from './routes/assets.routes.js';
import telemetryRoutes from './routes/telemetry.routes.js';
import decisionRoutes from './routes/decisions.routes.js';
import alarmRoutes from './routes/alarms.routes.js';
import dashboardRoutes from './routes/dashboard.routes.js';
import correlationRoutes from './routes/correlation.routes.js';
import visionRoutes from './routes/vision.routes.js';
import documentRoutes from './routes/documents.routes.js';
import logbookRoutes from './routes/logbook.routes.js';
import reportRoutes from './routes/reports.routes.js';
import adminRoutes from './routes/admin.routes.js';
import platformAdminAuthRoutes from './routes/platform-admin-auth.routes.js';
import platformAdminOrganizationsRoutes from './routes/platform-admin-organizations.routes.js';
import platformAdminSensorsRoutes from './routes/platform-admin-sensors.routes.js';
import platformAdminSensorTypesRoutes from './routes/platform-admin-sensor-types.routes.js';
import platformAdminDevicesRoutes from './routes/platform-admin-devices.routes.js';
import platformAdminDeviceTypesRoutes from './routes/platform-admin-device-types.routes.js';
import platformAdminGatewaysRoutes from './routes/platform-admin-gateways.routes.js';
import platformAdminGatewayTypesRoutes from './routes/platform-admin-gateway-types.routes.js';
import platformAdminProjectTemplatesRoutes from './routes/platform-admin-project-templates.routes.js';
import platformAdminAuditRoutes from './routes/platform-admin-audit.routes.js';
import healthRoutes from './routes/health.routes.js';
import deviceCommandRoutes from './routes/device-commands.routes.js';
import configManagementRoutes from './routes/config-management.routes.js';
import geospatialRoutes from './routes/geospatial.routes.js';
import { openApiSpec } from './openapi.js';
import { Notification } from './models/index.js';
import { requireAuth } from './middleware/auth.js';
import { asyncHandler } from './utils/async-handler.js';

export function createApp() {
  const app = express();
  app.locals.emitEvent = () => {};
  app.set('trust proxy', 1);
  app.use(correlationId);
  app.use(helmet({ crossOriginResourcePolicy: { policy: 'cross-origin' } }));
  app.use(compression());
  app.use(cors({ origin: true, credentials: true }));
  app.use(express.json({ limit: '50mb' }));
  app.use(express.urlencoded({ extended: true, limit: '50mb' }));
  app.use(morgan(env.nodeEnv === 'production' ? 'combined' : 'dev'));
  app.use('/api/', rateLimit({ windowMs: 60_000, limit: 600, standardHeaders: 'draft-7', legacyHeaders: false }));

  app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(openApiSpec));
  app.use('/api/v1', healthRoutes);
  app.use('/api/v1/auth', authRoutes);
  app.use('/api/v1/admin/auth', platformAdminAuthRoutes);
  app.use('/api/v1/admin/organizations', platformAdminOrganizationsRoutes);
  app.use('/api/v1/admin/sensors', platformAdminSensorsRoutes);
  app.use('/api/v1/admin/sensor-types', platformAdminSensorTypesRoutes);
  app.use('/api/v1/admin/devices', platformAdminDevicesRoutes);
  app.use('/api/v1/admin/device-types', platformAdminDeviceTypesRoutes);
  app.use('/api/v1/admin/gateways', platformAdminGatewaysRoutes);
  app.use('/api/v1/admin/gateway-types', platformAdminGatewayTypesRoutes);
  app.use('/api/v1/admin/project-templates', platformAdminProjectTemplatesRoutes);
  app.use('/api/v1/admin/audit', platformAdminAuditRoutes);
  app.use('/api/v1', templateRoutes);
  app.use('/api/v1', projectRoutes);
  app.use('/api/v1', assetRoutes);
  app.use('/api/v1', telemetryRoutes);
  app.use('/api/v1', decisionRoutes);
  app.use('/api/v1', alarmRoutes);
  app.use('/api/v1', dashboardRoutes);
  app.use('/api/v1', correlationRoutes);
  app.use('/api/v1', visionRoutes);
  app.use('/api/v1', documentRoutes);
  app.use('/api/v1', logbookRoutes);
  app.use('/api/v1', reportRoutes);
  app.use('/api/v1', adminRoutes);
  app.use('/api/v1', deviceCommandRoutes);
  app.use('/api/v1', configManagementRoutes);
  app.use('/api/v1', geospatialRoutes);
  app.get('/api/v1/notifications', requireAuth, asyncHandler(async (req, res) => {
    const rows = await Notification.find({ organizationId: req.auth.organizationId, recipient: req.auth.email }).sort({ createdAt: -1 }).limit(100).lean();
    res.json(rows);
  }));

  app.use(notFound);
  app.use(errorHandler);
  return app;
}
